controllers:
    resource: ../src/Controller/
    type: attribute

app_produtos:
    path: /produto/
    controller: App\Controller\ProdutoController::index

app_home:
    path: /home/
    controller: App\Controller\HomeController::index

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout